Repository red-hat-storage/ocs-sop, pull requests merged in 2021-09, with the labels that each got.

#21 fix storage capacity percentage in CephClusterCriticallyFull.adoc
  sop/modules/alerts/pages/CephClusterCriticallyFull.adoc
Labels: size/XS, lgtm

#22 Fix cluster access prerequisite and alert descriptions
  sop/modules/OSD/pages/CephOSDCriticallyFull.adoc
  sop/modules/OSD/pages/CephOSDDiskNotResponding.adoc
  sop/modules/OSD/pages/CephOSDDiskUnavailable.adoc
  sop/modules/OSD/partials/prerequisites.adoc
Labels: size/S

#23 Handling CephClusterReadOnlyMode
  sop/modules/OSD/partials/ocs_extend_cluster.adoc
  sop/modules/OSD/partials/procedure_resolution_expansion.adoc
  sop/modules/OSD/partials/procedure_resolution_expansion_readonly.adoc
  sop/modules/OSD/partials/troubleshoot_ceph_err.adoc
Labels: size/L
