Repository red-hat-storage/ocs-sop, pull requests merged in 2021-05, with the labels that each got.

#15 Add links to ODF architecture under Pre-requisites
  sop/modules/OSD/pages/CephClusterErrorState.adoc
  sop/modules/OSD/partials/prerequisites.adoc
Labels: size/S

#13 update ceph cluster err state SOP
  sop/modules/OSD/pages/CephClusterErrorState.adoc
  sop/modules/OSD/partials/gather_logs_cluster_err.adoc
  sop/modules/OSD/partials/prerequisites.adoc
Labels: size/S

#17 Check alert procedure for Dedicated
  sop/modules/OSD/pages/CephClusterCriticallyFull.adoc
  sop/modules/OSD/pages/CephClusterErrorState.adoc
  sop/modules/OSD/pages/CephClusterNearFull.adoc
  sop/modules/OSD/pages/CephClusterReadOnly.adoc
  sop/modules/OSD/pages/CephClusterWarningState.adoc
  sop/modules/OSD/pages/CephMdsMissingReplicas.adoc
  sop/modules/OSD/pages/CephMgrIsAbsent.adoc
  sop/modules/OSD/pages/CephMgrIsMissingReplicas.adoc
  sop/modules/OSD/pages/CephMonQuorumAtRisk.adoc
  sop/modules/OSD/pages/CephMonVersionMismatch.adoc
  sop/modules/OSD/pages/CephNodeDown.adoc
  sop/modules/OSD/pages/CephOSDCriticallyFull.adoc
  sop/modules/OSD/pages/CephOSDDiskNotResponding.adoc
  sop/modules/OSD/pages/CephOSDDiskUnavailable.adoc
  sop/modules/OSD/pages/CephOSDNearFull.adoc
  sop/modules/OSD/pages/CephOSDVersionMismatch.adoc
  sop/modules/OSD/pages/CephPGRepairTakingTooLong.adoc
  sop/modules/OSD/partials/prerequisites.adoc
Labels: size/M

#18 Update README.md
  README.md
Labels: size/XS

#19 Enhanced Ceph error state SOP
  sop/modules/OSD/pages/CephClusterErrorState.adoc
  sop/modules/OSD/partials/gather_logs_cluster_err.adoc
  sop/modules/OSD/partials/troubleshoot_ceph_err.adoc
Labels: size/M

#20 minor formatting correction
  sop/modules/OSD/partials/troubleshoot_ceph_err.adoc
Labels: size/S
